## README
To run the file, upload the data.csv file. In my case, I have uploaded it to sample_data folder in session storage. You can upload it elsewhere but remember to change the path mentioned in code afterwards.

# Multiple Linear Regression
### Using Gradient Descent

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
batch_size = 1000
learning_rate = 0.000001
num_of_epoch = 10000
test_training_ratio = 0.2
dataset_path = '/content/sample_data/data.csv'

In [ ]:
# Read the dataset
df = pd.read_csv(dataset_path) 
df.head()

In [ ]:
# Total_X is a matrix the size of 9568 X 4
total_X = df.iloc[:, :-1].values 

# Total_Y is a vector the size of 9568
total_y = df.iloc[:, -1].values  

In [ ]:
b = np.ones((total_X.shape[0],total_X.shape[1]+1)) # b is a 9568 X 5 matrix filled with ones.
b[:, 1:] = total_X #b is the total_X matrix except with first column filled with ones
total_X = b #reassign
print(total_X[:5])

[[1.00000e+00 8.34000e+00 4.07700e+01 1.01084e+03 9.00100e+01]
 [1.00000e+00 2.36400e+01 5.84900e+01 1.01140e+03 7.42000e+01]
 [1.00000e+00 2.97400e+01 5.69000e+01 1.00715e+03 4.19100e+01]
 [1.00000e+00 1.90700e+01 4.96900e+01 1.00722e+03 7.67900e+01]
 [1.00000e+00 1.18000e+01 4.06600e+01 1.01713e+03 9.72000e+01]]


In order for us to verify the accuracy later, we will reserve about 20% of the whole dataset.

In [ ]:
num_of_testing_example    = int(test_training_ratio*total_X.shape[0]) # (20/100) * 9568 = 1913.6. After flooring, 1913
num_of_training_example   = total_X.shape[0] - num_of_testing_example # 9568 - 1913 = 7655
X                         = total_X[:num_of_training_example] #matrix of size 7655 X 4. input X (according to the pdf note)
y                         = total_y[:num_of_training_example] #vector of size 7655. input y (according to the pdf note)
X_test                    = total_X[num_of_training_example:] #matrix of size 1913 X 4
y_test                    = total_y[num_of_training_example:] #vector of size 1913

In [ ]:
theta = np.random.rand((X.shape[1])) #randomly initialize theta as a vector of size 5

Parameters :

    data_point : Batches of rows in the training set matrix
    theta: theta vector

    Process : matrix (data points) multiplies vector (theta) 

    Output : prediction of the model, y_hat or h(X)

In [ ]:
def find_y_hat(data_point,theta):
    return np.dot(data_point, theta) 

In [ ]:
def testing_with_MSE():
    
    diff = X_test.dot(theta) - y_test #calculate (h(x) - y)
    
    loss = (1/(2*X_test.shape[0]))*(diff.dot(diff)) #calculate the loss using the defined equation
    
    print("Testing loss with MSE is : ", loss)
    
def testing_with_R2():
    
    diff = X_test.dot(theta) - y_test #calculates h(x) - y

    u = sum(np.square(diff)) #variance of the data from the prediction model
    v = sum(np.square(y_test - np.mean(y_test))) #variance of the original data

    print("The testing loss with R2 is :", (1 - (u/v))) #print the R2 coefficient


testing_with_MSE() #run the testing with MSE before the training begins
testing_with_R2() #run the testing with R2 before the training begins

In [ ]:
for epoch in range(num_of_epoch):
    
    diff = X.dot(theta) - y #calculate (h(x) - y)
    
    loss = (1/(2*X.shape[0]))*(diff.dot(diff))  #calculate the loss using the defined equation
    
    for index_first in range(0, X.shape[0], batch_size): #loop through the dataset with the given batch size
        
        index_last = index_first + batch_size #index_first - index_last = batch size
        index_last = None if index_last > X.shape[0] else index_last #if index_last > total no. of data points, it will be set to None
        
        y_hat = find_y_hat(X[index_first:index_last], theta) #predicted output
        
        m = y_hat.shape[0] # number of data points i.e. batch size
        
        y_hat_diff = y_hat - y[index_first:index_last] #calculate (h(x) - y)
        
        
        for j in range(theta.shape[0]): #gradient descent
        
            x_j = X[index_first:index_last, j] #get the x_j vector for that specified batch size
        
            par_der = (1/m)*(y_hat_diff.dot(x_j)) #calculate the partial derivative
            
            theta[j] = theta[j] - learning_rate*par_der
    
    if epoch % 1000 == 0: #print loss for every 500 epoch starting from 0th epoch
        print("Epoch : ", epoch)
        print("Loss : ", loss)
    

In [ ]:
print(theta)

In [ ]:
testing_with_MSE() #as expected gradient descent optimization works slightly worse than the normal equation method.
testing_with_R2()

In [ ]:
X_test.dot(theta)- y_test